var timeAct=90; timeIni=90; timeBon=5;
var successes=0; successesMax=5; attempts=0; attemptsMax=2;
var score=0; scoreMax=5; scoreInc=1; scoreDec=0
var typeGame=0;
var tiTime=false;
var tiTimeType=0;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=true;
var tiAttempts=false;
var tiScore=true;
var startTime;
var colorBack="#FFFDFD"; colorButton="#91962F"; colorText="#000000"; colorSele="#FF8000";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Verdana, Geneva, sans-serif";
var timeOnMessage=5; messageOk="Lo lograste!"; messageTime="Tiempo finalizado"; messageError=""; messageErrorG=""; messageAttempts=""; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="T1JERQ=="; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var words=["TG9zIG51bWVyb3MgbmF0dXJhbGVzIHNvbiBsb3MgcXVlIHVzYW1vcyBwYXJhIGNvbnRhcg==","RWwgbsO6bWVybyBhbnRlcmlvciBlcyBlbCBuw7ptZXJvIHF1ZSBlc3TDoSBhbnRlcyBkZSB1biBuw7ptZXJvIGN1YWxxdWllcmE=","RWwgbnVtZXJvIHBvc3RlcmlvciBlcyBlbCBxdWUgbGUgc2lndWU=","TG9zIG51bWVyb3Mgc29uIGluZmluaXRvcw==","TG9zIG51bWVyb3MgZXN0YW4gY29uZm9ybWFkb3MgcG9yIGRpZ2l0b3MgZGVsIDAgYWwgOQ=="];imaW=["naturales_n.jpg","images_nu.jpg","images.jpg","69.jpg","maxresdefault.jpg"];queW=["","","","",""];altW=["","","","",""];c=[52,70,38,25,52];
var infoW=["","","","",""];
var auW=["","","","",""];
var actMaxWidth="600"; actMaxHeight="300";indexG=0;profG=0;dirMedia="ORDE_resources/media/"; textBNext="";
var wordsG=[];imageW=[];questionW=[];audioW=[];cG=[];alterW=[];informaW=[];
